### PR TITLE
Bump up validator to v0.2.2

### PR DESCRIPTION
**Pull request by Sinclert**
This PR bumps up `hepdata_validator` dependency to `v0.2.2`. The new version of the validator does not break any existing functionality, it just adds support for remotely-defined schemas.

**Clarifications:**
- I treated the `data_schema` submission field as optional (check [here](https://github.com/Sinclert/hepdata/commit/b4b321ee852920b3b752df6cdc83a9ffb63b618d#diff-e4f3d23ca9cf3dde5022e99924b0bed1R546)).
- I have **not** bumped up the HEPData global version.

### CODE REVIEW

**Comment by Sinclert** [comment]
The CI obviously crashed because `hepdata_validator` v0.2.2 is not yet uploaded to PyPi.

I suggest merging [this PR](https://github.com/HEPData/hepdata-validator/pull/20) before publishing.

**Comment by Sinclert** [comment]
**Update:**

I just merged the master branch into this one, solving conflicts afterwards ✅ .

**Comment by Sinclert** [comment]
👆  It seems that the coverage decrease came from the Python3-compatibility branch merge. As [it also reported a 1.5% coverage decrease](https://github.com/HEPData/hepdata/pull/189#issuecomment-635246687).

**Comment by GraemeWatt** [comment]
> 👆 It seems that the coverage decrease came from the Python3-compatibility branch merge. As [it also reported a 1.5% coverage decrease](https://github.com/HEPData/hepdata/pull/189#issuecomment-635246687).

I think this is because [Travis CI](https://github.com/HEPData/hepdata/blob/d9a0119fe1392be397bc095fcabdc8939c353317/.travis.yml#L81-L83) omits the end-to-end tests for PRs from forked repositories.  I've just given you `Write` access to [HEPData/hepdata](https://github.com/HEPData/hepdata), so in future you can open a PR from a branch of the main repo and the end-to-end tests will run from the PR.  After the merge of #189 to `master`, coverage actually [increased by 0.1%](https://coveralls.io/builds/31414320), even though the PR reported a [decrease of 1.5%](https://coveralls.io/builds/31413878).

**Pull request closed without merging**
