### PR TITLE
Updates to work with hepdata-validator v0.2

### PR DESCRIPTION
**Pull request by alisonrclarke**
See https://github.com/HEPData/hepdata-validator/pull/6/files

This change ensures the schema URLs will work after the above PR is merged to master; it should be released at the same time as the PR is merged.

### CODE REVIEW

**Comment by alisonrclarke** [comment]
Actually I've realised that the symlinks in the latest commit of hepdata-validator mean there's no rush to update this after the push to master on hepdata-validator.

**Review by GraemeWatt — CHANGES_REQUESTED** [review]
Before these calls to the `convert` function:
https://github.com/HEPData/hepdata/blob/af823b6340c5aaedb301ac5eb22064d0420077c0/hepdata/modules/converter/__init__.py#L61-L67
https://github.com/HEPData/hepdata/blob/af823b6340c5aaedb301ac5eb22064d0420077c0/hepdata/modules/converter/views.py#L524-L530
you should pass:
```python
options['validator_schema_version'] = '0.1.0'
```
so that the converter uses the old schema version for validation.  This was the original reason why we needed to introduce versioning of JSON schema, to avoid breaking conversion for old uploads.

**Comment by alisonrclarke** [comment]
> Before these calls to the `convert` function:
> 
> https://github.com/HEPData/hepdata/blob/af823b6340c5aaedb301ac5eb22064d0420077c0/hepdata/modules/converter/__init__.py#L61-L67
> 
> 
> https://github.com/HEPData/hepdata/blob/af823b6340c5aaedb301ac5eb22064d0420077c0/hepdata/modules/converter/views.py#L524-L530
> 
> 
> you should pass:
> ```python
> options['validator_schema_version'] = '0.1.0'
> ```
> 
> so that the converter uses the old schema version for validation. This was the original reason why we needed to introduce versioning of JSON schema, to avoid breaking conversion for old uploads.

This PR was just to ensure the latest version of the validator package worked OK (especially the redirects). I think this is a separate issue to working with the latest version of the converter?

**Comment by GraemeWatt** [comment]
> This PR was just to ensure the latest version of the validator package worked OK (especially the redirects). I think this is a separate issue to working with the latest version of the converter?

Yes, I agree after thinking about it a bit more.  I'll merge this PR now, then the above changes to the `convert` function would only be needed after a new `hepdata-converter-ws` Docker container is deployed.

**Comment by alisonrclarke** [comment]
See #188 for issue about updating for hepdata-converter.

**Pull request merged**
