### PR TITLE
Fixing travis so It'll work with newer version of hepdata-converter

### PR DESCRIPTION
**Pull request by michal-szostak**
I fixed travis file. Now it installs root + python bindings and compiles yoda from source. It works with new docker based architecture supporting sudo (it's an experimental feature, but works great most of the time (the only problem it that sometimes during docker initialization some network problems can occur and thus failing the build - simply restarting it fixes it) @jstypka - thanks for pointing out this new travis feature). It also provides new added benefit of running on Ubuntu 14.04, instead of 12.04 which is good for all of us.

This branch is still failing with command:
```
The command "inveniomanage hepdata_records populate > /dev/null 2>&1" failed and exited with 1 during .
```
 
But I believe that this bug was there from the beginning (someone can confirm? @eamonnmag ? - I hope that I didn't break anything inside invenio / hepdata), 

As for now the travis build installs hepdata-converter without any problems, so I advise to merge this branch as soon as possible.

### CODE REVIEW

**Comment by eamonnmag** [comment]
populate is working, will need to take a look at it tomorrow.

**Comment by michal-szostak** [comment]
I changed Yoda version to 1.5.1 (fixed Point3D issue). Any news about that travis error? Did it happen before?

**Comment by eamonnmag** [comment]
The only thing that was added yesterday is a check to ensure that the submission does not already exist in the index. This *could* be the reason, but I don't know without seeing the error.

**Comment by jstypka** [comment]
Will look at that today

**Comment by jstypka** [comment]
This pull request can be closed, after all we will separate the hepdata-converter as an another web service. Correct? @eamonnmag @michal-szostak

**Pull request closed without merging**
