### PR TITLE
hepdata_records: don't round errors given in scientific notation

### PR DESCRIPTION
**Pull request by GraemeWatt**
- Previous commit (ea5daea6d80297a49143f25241e107dfcb22440d) doesn't work for errors in scientific notation, so don't try to round.  Example: [ins1296835](http://hepdata.cedar.ac.uk/view/ins1296835/d1)
- Also correct date format for submissions with a commit message (version 2 or greater).

Signed-off-by: Graeme Watt graeme.watt@durham.ac.uk

### CODE REVIEW

**Comment by eamonnmag** [comment]
Good catch on the scientific notation.

**Comment by GraemeWatt** [comment]
Just realised that my commit works if both the central value and errors are given in scientific notation, but it might fail if the errors are given as normal numbers and the central value is given in scientific notation.  Or if the central value is given as normal numbers, but the errors are given in scientific notation then they could still be rounded.  So probably it's better to try and make the rounding more robust rather than just merging this commit.  Also, I don't think you currently round errors given as percentages.  I'll try to improve the code.

**Comment by eamonnmag** [comment]
This is a pain. Are you happy to work on this rounding? I'm rather busy on
closing some other issues.

**Comment by eamonnmag** [comment]
Hi @GraemeWatt, thanks! Will pull and test this in the next few hours.

**Pull request merged**
