### PR TITLE
hepdata_records: change display of asymmetric errors and add link to old HepData

### PR DESCRIPTION
**Pull request by GraemeWatt**

### CODE REVIEW

**Comment by GraemeWatt** [comment]
Thanks for merging, @eamonnmag, but you missed changes to two lines in `dataviewer.js`:
```
errors_obj.err_plus = Math.max(down_err, up_err, 0);
errors_obj.err_minus = Math.min(down_err, up_err, 0);
```
I added the `0` to account for the (unusual) case where both errors have the same sign, e.g. both positive, then the minus error should be zero not the smallest positive error.

**Comment by eamonnmag** [comment]
Ah OK. Missed that!

**Comment by GraemeWatt** [comment]
Something went wrong with the merge and the new CSS styles to display asymmetric errors with the `plus` above the `minus` are not being applied.  @eamonnmag, can you please fix this?

Also, please correct the two lines above and remove a duplicate line from `dataviewer.js`:
```
var min_error = HEPDATA.visualization.utils.round(errors[error_idx]['asymerror']['minus'], 2);
```

**Comment by eamonnmag** [comment]
All done.

**Comment by eamonnmag** [comment]
Deploying the new version now.

**Pull request merged**
