### PR TITLE
Add data keywords to data table docs in elasticsearch

### LINKED ISSUE #349: search: keywords search doesn't match data tables
e.g. searching for: **reactions:"P P --> LQ LQ X"** returns one record (https://www.hepdata.net/record/ins1462258) but with "0 data tables match query", but searching for **"P P --> LQ LQ X"** returns the same record with "4 data tables match query".

This is because a keywords search only matches against the `data_keywords` field, which is only added to elasticsearch for publications, not data tables.

Adding `data_keywords` fields to each data table should improve the results (but we should check for any unwanted side effects).

### PR DESCRIPTION
**Pull request by alisonrclarke**
Fixes #349

Submissions will need to be reindexed before this takes effect, but it shouldn't cause any issues before reindexing is complete.

### CODE REVIEW

**Comment by GraemeWatt** [comment]
Thanks, that seems to work on my local instance after running `hepdata utils reindex`.  I get some error messages like `Task hepdata.ext.elasticsearch.api.reindex_batch[833bc09d-8cac-4bf9-a1d6-c7914fb79b3d] retry: Retry in 30s: AttributeError("'Hit' object has no attribute 'data_keywords'",)`.  Is that anything to worry about?  Or should I have run `hepdata utils reindex --recreate True` to recreate the index?  (I prefer to avoid using this option in production, because it leads to users seeing apparently missing records during reindexing.)  In any case, it looks like the `data_keywords` were added correctly without recreating the index.

**Comment by alisonrclarke** [comment]
You shouldn't need to recreate the index I don't think. Can you get a stack trace so I can see where it's happening? I can see that if a data table has no keywords we might need to check before getting the `data_keywords` property, but 'keywords' is a required property in the schema so I wonder if something else is going on.

**Comment by alisonrclarke** [comment]
As @GraemeWatt pointed out, the issue with missing `data_keywords` was due to reindexing in batches by record id, which meant that not all of a publication's data tables were indexed at the same time as the publication itself. I've now refactored `reindex_all` and `reindex_batch` to reindex publications and data tables at the same time.

Tested locally by reverting to master and recreating the index, then switching to this branch and reindexing without recreating the index.

**Comment by GraemeWatt** [comment]
Thanks for refactoring.  Looking at the new code, I wonder if further improvements could be made in `reindex_all` to filter out records that should not be indexed, for example, superseded versions, Sandbox records, unfinished records.  As I understand it, the Elasticsearch index only stores the latest finalised version of a record, not earlier versions.  The current code uses `index_record_ids` to avoid indexing Sandbox or unfinished records, but it would be better if a check for `overall_status='finished'` was made when filtering the `HEPSubmission` object in `reindex_all`.  If there are multiple finished versions with the same `publication_recid`, only the latest version should be indexed.  In `reindex_batch` only the data tables with the same `version` and `publication_recid` as the `HEPSubmission` object should be indexed.  It should also be checked that the code works for a finished record with no data tables.

**Review by GraemeWatt — APPROVED** [review]

**Pull request merged**
