### PR TITLE
Remove migrator

### LINKED ISSUE #276: records: remove code used in 2016 for migrating from hepdata.cedar.ac.uk
The migration code used in 2016 is no longer essential and should be removed from the codebase.  Relevant code is mostly in the [records/migrator](https://github.com/HEPData/hepdata/tree/master/hepdata/modules/records/migrator) module, although that module also contains unrelated functions such as `update_analyses()`.  Occasionally, it's necessary to repeat migration of a particular record, for example, if the original migration in 2016 partially failed and did not move all tables.  However, this task could be performed by downloading a single `.yaml` file from http://hepdata.cedar.ac.uk and manually uploading to https://hepdata.net.  Before removing the migration code, it would be useful to have a method of populating a developer's local instance with records, i.e. a replacement for `hepdata utils load` (see #275).

### PR DESCRIPTION
**Pull request by alisonrclarke**
Fixes #276 

Currently this work sits on top of PR #302 which isn't yet merged. I can rebase on top of master if you want to merge #302 first.

### CODE REVIEW

**Comment by GraemeWatt** [comment]
Yes, I'll merge #302 first.  In the Zulip chat last week, you asked whether we should remove [download_resource_file](https://github.com/HEPData/hepdata/blob/15a7145b1d56902520dcfde053f76fd90680dfba/hepdata/modules/records/utils/resources.py#L34) which refers to hepdata.cedar.ac.uk.  I responded that it should be removed and an error returned where it's called from [parse_additional_resources](https://github.com/HEPData/hepdata/blob/15a7145b1d56902520dcfde053f76fd90680dfba/hepdata/modules/records/utils/submission.py#L346).  But these files migrated from hepdata.cedar.ac.uk are stored in a separate `resources` directory and not included in the zip file.  So I think something similar to `download_resource_file` will be needed by the importer when downloading these resources files from hepdata.net into a new instance.

**Comment by alisonrclarke** [comment]
> But these files migrated from hepdata.cedar.ac.uk are stored in a separate `resources` directory and not included in the zip file.

Ah. I hadn't appreciated that when implementing #110, so the 'Download with resources' doesn't include the additional resources in these cases (e.g. I just tried https://www.hepdata.net/record/ins1320775). I've logged #306 and will fix that first. Hopefully that should then sort this issue out?

**Comment by alisonrclarke** [comment]
This is going to need a bit more work following #308 as we'll need to reproduce a test record with a 'resources' directory to ensure the tests continue to work. This facility could be useful for developers too, so they can have some records locally that look like the migrated ones on hepdata.net.

**Comment by alisonrclarke** [comment]
Latest commits add a method to create a record that has the same directory structure as records on hepdata.net that were migrated from hepdata.cedar.ac.uk, from a zip. It's used in one of the tests and also on the command line. Currently it's only possible to add a single record, ins1299143.

@GraemeWatt A few questions:

1. Does this look like a sensible approach? 
2. Is it worth adding zips for a couple more records and adding an inspire_id parameter to `mock_import_old_record`?
3. Should we call `mock_import_old_record` from the `initialise_db.sh` script as well as importing records via the importer?

**Comment by GraemeWatt** [comment]
Looks good.  Yes to all three questions.  Few other comments:

* I've tested `hepdata importer bulk-import-records` now that the `/search/ids` endpoint is available on [hepdata.net](https://www.hepdata.net).  It works, but I have a problem importing the latest record (https://www.hepdata.net/record/ins778396).  It looks like the directory of files is created, but then files are deleted before the `submission.yaml` file has been processed, giving errors.  The data directory `7f/960/1612967046/HEPData-ins778396-v2-original/` contains only three files (`rhs1_auau.yaml`, `rhs1_pp.yaml`, `submission.yaml`) instead of the whole contents of the downloaded `HEPData-ins778396-v2-original.zip` file.  I've tried several times also using `hepdata importer import-records` and unloading the failed record, but I get the same errors.  Can you please check if it works on your local instance?

* Can you please add a `send_email` option (default: `False`) to the new CLI commands (`bulk-import-records`, `import-records`, `create-mock-migrated-record`)?  Otherwise it could get annoying for a large number of imports if a developer has email enabled.

* Can you please make the Celery Beat tasks in `CELERY_BEAT_SCHEDULE` only applicable in production?  A local instance gives errors if the records from Rivet or INSPIRE are not loaded.

* There's a debug statement `breakpoint()` in `create_mock_migrated_record()` of `hepdata/cli.py`.  This isn't available in my Python 3.6 (also used in production), but I checked the function works if I remove the `breakpoint()`.

* I guess we should also remove references to [hepdata.cedar.ac.uk](http://hepdata.cedar.ac.uk) throughout the code:

  - Remove https://github.com/HEPData/hepdata/blob/69b930fedfe9d215500e9d6964132ddf3f4ed044/hepdata/modules/records/templates/hepdata_records/components/uploader_info.html#L15-L16
  - Remove hyperlink from https://github.com/HEPData/hepdata/blob/69b930fedfe9d215500e9d6964132ddf3f4ed044/hepdata/modules/records/templates/hepdata_records/components/uploader_info.html#L21-L22
  - Remove https://github.com/HEPData/hepdata/blob/69b930fedfe9d215500e9d6964132ddf3f4ed044/hepdata/modules/theme/templates/hepdata_theme/home.html#L81-L83
  - Remove https://github.com/HEPData/hepdata/blob/69b930fedfe9d215500e9d6964132ddf3f4ed044/hepdata/modules/records/templates/hepdata_records/data_record.html#L152-L162
  - Remove https://github.com/HEPData/hepdata/blob/69b930fedfe9d215500e9d6964132ddf3f4ed044/hepdata/modules/records/templates/hepdata_records/publication_record.html#L200-L209

**Comment by alisonrclarke** [comment]
>  I've tested `hepdata importer bulk-import-records` now that the `/search/ids` endpoint is available on [hepdata.net](https://www.hepdata.net).  It works, but I have a problem importing the latest record (https://www.hepdata.net/record/ins778396).  It looks like the directory of files is created, but then files are deleted before the `submission.yaml` file has been processed, giving errors.  The data directory `7f/960/1612967046/HEPData-ins778396-v2-original/` contains only three files (`rhs1_auau.yaml`, `rhs1_pp.yaml`, `submission.yaml`) instead of the whole contents of the downloaded `HEPData-ins778396-v2-original.zip` file.  I've tried several times also using `hepdata importer import-records` and unloading the failed record, but I get the same errors.  Can you please check if it works on your local instance?

Think I've figured out what's going on. The import fails because there are two PNGs missing (rhs1.png, thumb_rhs1.png) - it looks like they're missing on hepdata.net too? In such cases the importer deletes the unzipped dir and tries again using the old schema. What I hadn't tested is a case like this where it gets as far as creating data tables before failing. `cleanup_submission` is called from `process_zip_archive` and deletes the existing tables, and therefore also the associated files, which in this case are in an identically-named folder to the previous attempt. Calling `cleanup_submission`   before retrying does the trick and returns a sensible error message.

**Comment by GraemeWatt** [comment]
Thanks for investigating.  The record https://www.hepdata.net/record/ins778396?version=2 is a complicated case that I haven't seen before.  The files `rhs1.png` and `thumb_rhs1.png` are present in the original upload (otherwise it would have failed).  It seems that the table named "Figure 7, p + p collisions" appears twice in the `submission.yaml` file, the first time with the two image files as `additional_resources` and the second time without.  During the processing, the image files must be deleted somehow, so they were not included in the packaged zip file.  I've made a temporary fix by repackaging the zip file to include the two missing image files, so that the import now works.  I've opened new issues HEPData/hepdata-validator#24 and #311 to check for duplicate tables.  I also found an unrelated problem #312 with the same record.

If the import fails, can you please unload the record, since it's currently left in a partially processed state?

Some older records on [hepdata.net](https://www.hepdata.net) might also have missing files included as `additional_resources` or fail the most recent `DataFileValidator` check.  (Your `old_submission_schema` flag only applies to the `SubmissionFileValidator`.)  But for now I think it's fine just to let the import fail, rather than attempt to support the import of all possible records from [hepdata.net](https://www.hepdata.net).

Not all points of [my last comment](https://github.com/HEPData/hepdata/pull/305#issuecomment-776797626) have been addressed yet.  Could the `send_email` option also be added to the `create_mock_migrated_record` command?

**Comment by alisonrclarke** [comment]
> Some older records on hepdata.net might also have missing files included as additional_resources or fail the most recent DataFileValidator check. (Your old_submission_schema flag only applies to the SubmissionFileValidator.) But for now I think it's fine just to let the import fail, rather than attempt to support the import of all possible records from hepdata.net.

Would it be worth using the old schema for both the submission and data validators? So we try just once more but with both old schemas?

**Comment by GraemeWatt** [comment]
> Would it be worth using the old schema for both the submission and data validators? So we try just once more but with both old schemas?

Yes, you could change this line:

https://github.com/HEPData/hepdata/blob/0f13d4b2ba5b84429bd19c1b1f4d1d4f21dd27cf/hepdata/modules/records/importer/api.py#L182

to:

        errors = process_zip_archive(file_path, recid, from_oldhepdata=True, old_submission_schema=True)

and propagate the `from_oldhepdata` variable from `process_zip_archive` to `process_submission_directory`.

It's probably worth renaming the `from_oldhepdata` variable as `old_data_schema` for clarity and symmetry with `old_submission_schema`, and also rename `old_hepdata` as `old_schema` in the definition of `get_data_validator`.

**Comment by GraemeWatt** [comment]
Sorry, another request.  At the end of `process_saved_file` the code calls `cleanup_old_files(hepsubmission)` to delete redundant data files and DB entries if there have been multiple uploads.  Can you please do the same at the end of `_import_record`?  Otherwise if the latter is called with `update_existing=True`, old directories can be left on the disk.  This was something I noticed when testing previously.

**Review by GraemeWatt — APPROVED** [review]
I've checked that all my comments have now been addressed, so I'll merge now.  Thanks a lot!

**Pull request merged**
