### PR TITLE
Updates to DOI minting

### LINKED ISSUE #225: datacite: update metadata schema to latest version 4.4
HEPData currently uses Version 3 of the [DataCite Metadata Schema](http://schema.datacite.org).  A request from Artemis Lavasa (@ArtemisLav) was made on 26th June 2020:

> As part of our relationship with DataCite, we are required to adhere to certain guidelines. There are a few action items that came up recently that I would like to ask each of you to address for your client accounts as soon as possible. More specifically, for each account:
> - Support the submission of metadata to DataCite that is compliant with DataCite Metadata Schema 4 or a more recent version. That means that if you are currently using version 3 of the schema or older, you will need to move to the newest one.

### LINKED ISSUE #318: datacite: refactor generate_dois_for_submission into multiple Celery tasks
The `generate_dois_for_submission` function is run as a Celery task to register DOIs and push metadata to DataCite for both the whole submission (`create_container_doi`) and individual tables (`create_data_doi`).  This can take a long time for records with hundreds of data tables, so some kind of parallelisation would help to speed things up, for example, by running `create_container_doi` and `create_data_doi` as separate Celery tasks.  With the retry strategy implemented in PR #316, it would also be more efficient just to retry individual failed DOIs and not all DOIs associated with a submission.  (It often happens that only one or two DOIs fails out of several hundred.)  However, because both `create_container_doi` and `create_data_doi` take `HEPSubmission` and `DataSubmission` objects as arguments, they cannot be run as Celery tasks in their current state.  A refactoring would be necessary to move the database calls inside the functions, possibly making them less efficient.  It would also need to be checked whether the DataCite API would cope with pushes from multiple Celery workers simultaneously.

### LINKED ISSUE #377: datacite: use collaboration name as "creator" instead of individual authors
The XML metadata pushed to DataCite ([datacite_container_submission.xml](https://github.com/HEPData/hepdata/blob/master/hepdata/modules/records/templates/hepdata_records/formats/datacite/datacite_container_submission.xml) and [datacite_data_record.xml](https://github.com/HEPData/hepdata/blob/master/hepdata/modules/records/templates/hepdata_records/formats/datacite/datacite_data_record.xml)) includes the full list of authors as `creators`.  We had a request from the [Data Citation Index](https://clarivate.com/webofsciencegroup/solutions/webofscience-data-citation-index/) to include the collaboration name in the XML metadata.  This could be done using, for example, "ATLAS Collaboration" as `creatorName` and "Organizational" as `nameType` **instead** of the full list of authors, drastically reducing the size of the XML metadata for large collaborations consisting of thousands of authors.  Multiple collaborations should each have a `creator` entry.  If there is no collaboration, the full list of authors can be given as before, but with "Personal" as `nameType`.  I've checked with Artemis Lavasa (DataCite manager at CERN) that this solution is acceptable, and it has in fact been followed for years by CERN Open Data.  This issue should be addressed with #225, i.e. updating the DataCite metadata schema version.  Reducing the XML metadata size might also help with the problem mentioned in #318, i.e. failures when pushing XML metadata to DataCite.  After this issue is closed and the new code deployed, it will be necessary to run `hepdata doi-utils register-dois` to push the updated XML metadata to DataCite for all finished records.

### PR DESCRIPTION
**Pull request by alisonrclarke**
* Fixes #225 
 * Fixes #377 
 * Fixes #318 

The change introduces a new celery queue `datacite` for DataCite tasks. Before deploying the Kubernetes config will need to be updated to create new workers to run these queue, and updated config values, where `DATACITE_QUEUE_WORKERS` matches the number of datacite celery worker pods in Kubernetes:

```
DATACITE_QUEUE_WORKERS = 10 # Number of workers running the datacite queue
CELERY_TASK_ANNOTATIONS = {
    '*': {
        'acks_late': True,
        'reject_on_worker_lost': True,
        'autoretry_for': (Exception,),
        'default_retry_delay': 30
    },
    'hepdata.modules.records.utils.doi_minter.create_container_doi': {
        'rate_limit': f"{100 / DATACITE_QUEUE_WORKERS}/m"
    },
    'hepdata.modules.records.utils.doi_minter.create_data_doi': {
        'rate_limit': f"{500 / DATACITE_QUEUE_WORKERS}/m"
    },
}
```

### CODE REVIEW

**Comment by alisonrclarke** [comment]
Realised the current PR allows for the possibility of a race condition between `create_container_doi` reserving the DOIs for data submissions (and adding them to the db) and `create_data_doi` attempting to register them. Will rethink.

**Comment by GraemeWatt** [comment]
Yes, maybe the calls to `reserve_doi_for_hepsubmission` and `reserve_dois_for_data_submissions` need to be moved to `generate_dois_for_submission`, which should also be a rate-limited task run from the `datacite` queue.

**Comment by alisonrclarke** [comment]
> Yes, maybe the calls to `reserve_doi_for_hepsubmission` and `reserve_dois_for_data_submissions` need to be moved to `generate_dois_for_submission`, which should also be a rate-limited task run from the `datacite` queue.

I'm currently working around this by determining the DOI values up front and passing them around in the other functions. However, on further investigation I don't think the `reserve_...` calls actually reserve anything with DataCite; they just put the DOIs in the DB (on the submission object and in the pidstore). (See https://github.com/inveniosoftware/invenio-pidstore/blob/master/invenio_pidstore/providers/datacite.py.) So we could probably just move the calls to `reserve_...` into `generate_dois_for_submission` without modifying the queues.

**Comment by GraemeWatt** [comment]
> However, on further investigation I don't think the `reserve_...` calls actually reserve anything with DataCite; they just put the DOIs in the DB (on the submission object and in the pidstore). So we could probably just move the calls to `reserve_...` into `generate_dois_for_submission` without modifying the queues.

Yes, you're right, I was thinking about this after I sent the last message.  The `DataCiteProvider.create(doi)` call only creates an entry in the internal DB, but doesn't use the DataCite API.  Do you still need `NO_DOI_MINTING = False` added in https://github.com/HEPData/hepdata/pull/404/commits/2f38646cd2b184ea3a2f1589dfebc4a6846d378d given that you're mocking the DataCite API response in the tests?  Unrelated, but could the `hepdata-validator` version be bumped to 0.3.1 in this PR?

**Comment by alisonrclarke** [comment]
> Do you still need `NO_DOI_MINTING = False` added in [2f38646](https://github.com/HEPData/hepdata/commit/2f38646cd2b184ea3a2f1589dfebc4a6846d378d) given that you're mocking the DataCite API response in the tests?

I'm only mocking it in the `doi_minter.py` tests, so I think it's probably safer to leave it in in case other tests which import, create or finalise records get as far as `doi_minter.py`.

**Comment by GraemeWatt** [comment]
This looks good.  Is it ready to be merged now?  I've checked that I can mint DOIs with the DataCite test account using this branch.  I think we can remove `TEST_DOI_PREFIX = "10.5072"` from `config.py` as it is not used anywhere (e.g. removed in https://github.com/inveniosoftware/datacite/commit/272570753b5623824a5f3f9ee981517c36a8a618).  Also the `PIDSTORE_DATACITE_URL = "https://mds.datacite.org"` can probably be removed since it's the default value, unless `PIDSTORE_DATACITE_TESTMODE = True` then `https://mds.test.datacite.org/` will be used instead.

**Review by GraemeWatt — APPROVED** [review]

**Pull request merged**
